language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: pEC9s+ijIp8+RLhqw6p10oXL0j+vsxzrOe7xbHGUB7qdtcJXUlJQIiLnVuozvsNJ4emgunT6IF/MWED9Cg5Y6t5ItbBcNNvK3tfIj3DmTJtDqoFIE7GV1dqa647Xq9nsWUqit8R+0tbuRZ6HPmj4rglBt2k2n0BtljhjNIHPctMSfL29mJEzqHJyxrBmWRbfDV0VKOaifZcK8fns7vbERARwrRmtibSUFYso6Cy0pXtWbT9OvaMSQe1Atd6qcCOQ6yidNBnNnzozJpkpM0SRnHsYVtPv7+T0oSAmrZB/vL18DxhI4V8bx/N+kA3bEX0ACuYk1CnNHRs9x+QqCbvlMVT9AEYlak986YZCTWs2p+3hsbquOyNaKI3uPt2Y4v4IWoTvQ1intOxq4MftWrCkH1cAIemn6RKAg+JmPjfZgmIV8TDai97N4O2qWaShWi55dxyrMFBdE/vqFgpO3gn0rE2WTDA56823gXdRVV+uD415GnmF9GAtGI/5QpsJJvd6R4d4+X5bi0YamAcI+O8u+Eu/NBvmV+ENeP05ExpXX6+JZuVxOY58nvMeH8YMaUWRZyqL8HWU/1rT3XSfctnjg1v0ejKq7StV6yTbi9XLT6T1Hd9HgUf21lYgHhWDtIRIw1vopunxgsdOQPsjLQQqO9o8B4ZdMV6jKRZ6w12FJxw=
  app: ancient-gorge-94562
  on:
    repo: rohinieravi/node-shopping-list-integration-tests
