language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: hdn/eG8m/BrzM0ZH85xKjC60g84p0X8KFANnZnuAEPQgxaRETWtVKrnI5OVa0FRa4bXAPUVpVgxPWiqYVL/IEG5UOFE1hIE7M05C3raKtGChA90LNhsDbTJFlPhaQyEwL++7SURASuPyufzx4Qx5UWoWgcO1B3mib2baT2U3hkEpqyJamHb/pz8lK+bdOElTZ9phfh9KmgU5drmKMNUhjaArXVu2P2AIHNjtWXdw+yawFi4gVp9TxUYsz08Rs0DWrAofaihh/V2nX48SoHMlGt4/ROd1o6Jqbn4xQLmUgszEL1mHrlIVKUHASzVAoL8sCk6IdXEiBneDyZhHBzKletL3ZdkjYP6SVp9BhMb4WQIpBySzQxBnh+hStVyHl1wno5nrObXm7Wall0V6R7VfONl4jiSmsuM2udXlm0jEJUrBCMMfu2CP4xfECGZ5ORf8FAdTFue9F3SnRIR0lFsTVPysiS+EmUCRh/TMfUBS+Rl60D0OMsjI2fwhKRKs5yNUp7tr/BvYSfxzU7lJTmKIc/w8TO7oEmIVWn+ZRcFc7vC5fxdLduxKd4Xd82NY8ossbPafhEUKp6NQXjtCDP6LcYS1Itpj45lGt1ZSVA9SK5bOqKfgKEN7FGq8HLbuBHUVRe6vRNL4zxoj7q7ydQ1LG+OBVlEeLAUmZWuvkPxaHXQ=
  app: shielded-brushlands-40980
  on:
    repo: rohinieravi/node-shopping-list-integration-tests
